### ISSUE TITLE
Serious TPS Freedom-diving

### ISSUE THREAD

**Issue by KurumiFake** [ThiccMC/AlynaaMC#6]
UnstableCity experienced seroius issue with performance using AlynaaMC, smh using Paper solved the problem
its so bad that it crashes the entire server and wipe out players's inventory btw

**Comment by KurumiFake** [comment]
serious*

**Comment by KurumiFake** [comment]
and it always crash wo giving out any log nor crash report, nor a timings report or spark profiler, kinda no proof here
![Screenshot_2021-12-11-21-12-23-33](https://user-images.githubusercontent.com/86518350/145681748-95e11380-54fb-4b9a-ac1b-87dbe740ec98.png)

**Comment by QuanTrieuPCYT** [comment]
also happened with Asteria SMP, will look into the issue.

**Comment by QuanTrieuPCYT** [comment]
Seems to be fixed, closing...
